# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mov-10',
                'doc_host': 'https://daveramseymusic.github.io',
                'git_url': 'https://github.com/daveramseymusic/mov-10',
                'lib_path': 'mov_10'},
  'syms': {'mov_10.recommender': {'mov_10.recommender.foo': ('mov_recommender_attempt.html#foo', 'mov_10/recommender.py')}}}