# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mov-10',
                'doc_host': 'https://daveramseymusic.github.io',
                'git_url': 'https://github.com/daveramseymusic/mov-10',
                'lib_path': 'mov_10'},
  'syms': {'mov_10.core': {'mov_10.core.foo': ('core.html#foo', 'mov_10/core.py')}}}